### ISSUE TITLE
modelo de cv - primer empleo IT

### ISSUE THREAD

**Issue by Valtory** [sysarmy/disneyland#107]
# Modelo cv para primer empleo en IT

* el diseño es el siguiente:
[:D](https://drive.google.com/file/d/1fDN1YjhCCXrY8wfmO-v-YNDZAwb0QqjL/view?usp=sharing)

* el archivo para editarlo:
[:D](https://drive.google.com/file/d/1yqPUBdWp9bYzGSKiS2wpI3ttjR0XHw_y/view?usp=sharing)

El editable está en formato psd, que es photoshop, pero de todas formas google te permite acceder a [Photopea](https://www.photopea.com/) para editarlo en el browser.
Realmente es muy sencillo, es cuestion de encontrar los textos y reemplazarlos.

**Comment by edux** [comment]
Mete un pull request con esto y lo mergeamos.

**Comment by wlensinas** [comment]
Creo que aplica a todo el cv. Esta muy bueno :D
