### ISSUE TITLE
agregar a #shithappens

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#109]
https://status.umbrella.com/#/

**Comment by Nachichuri** [comment]
Buenas! Avisame si puedo dar una mano :)

**Comment by edux** [comment]
La verdad no recuerdo que vi de util de esto, porque mirandolo es muy cisco centric. Quizas fue cuando hubo algun major outage, ahora no le veo mucho sentido, vos le ves algo @Nachichuri ?

**Comment by Nachichuri** [comment]
Sacando la ironía de que pueda aparecer en #shithappens cuando ellos mismos afirman que "_your organization is never disrupted by planned or unplanned outages_", creo que no le veo nada super interesante... Es verdad, bastante Cisco centric.

**Comment by edux** [comment]
Sep, al pedo, gracias.
