### ISSUE TITLE
charla sobre DevOps 20220321 #sysarmy #help 

### ISSUE THREAD

**Issue by Daniel-DZ** [sysarmy/disneyland#119]
brunovianco
Buenas, ¿alguien tiene info o material de lectura sobre procesos en DevOps?, onda ISO 27K/ITIL

yaco06
libros sobre esto hay muchos, si es para vos te tiro unos títulos, pero si es para una empresa, puede ser que mostrando los libros de google te lo reciban mejor

https://cdn.discordapp.com/attachments/746006753262567466/955413310969360414/unknown.png
https://www.amazon.com/DevOps-Handbook-Second-World-Class-Organizations/dp/B09L56CT6N

https://cdn.discordapp.com/attachments/746006753262567466/955414138820124692/unknown.png
https://www.amazon.com/DevOps-Paradox-truth-about-people/dp/1789133637

https://cdn.discordapp.com/attachments/746006753262567466/955415254760828938/unknown.png
https://www.amazon.com/-/es/Murat-Erder/dp/0136523560

brunovianco
@yaco06 genial, gracias, es para una empresa pero la idea es arrancar por algún lado y definir procesos, ¿cual recomendarías como para empezar?

jedux
pero ya tenes madurez para para practicas de sre?
mirá es un tema complejo porque si tenés una infra basada en silos, a la vieja escuela, pasar a una cultura devops es un proceso en sí
^esto

yaco06
algunas cosas se pueden migrar, otras no, hay que ver cómo están organizados los empleados, etc.
por ejemplo, si contrataste programadores e introducís una infra de CI/CD y hacés responsables a los developers de atender tickets, entonces ya los tenés que meter en oncall
y hay que ver si las posiciones para las que firmaron incluyen oncall o no

jedux
si tuviera que adivinar, empezaria por cosas que sumen visibilidad a bajo costo, que el monitoreo, graficos, etc. sea util y que cualquiera los pueda consumir.

yaco06
pero no es imposible sortear obstáculos, mientras vas aggiornando las nuevas contrataciones a una cultura devops, podés seguir manejando tickets de apps igual que antes, con la gente de infra atendiendo oncall, reiniciando servicios, contactando a devs para que los asistan (algo de eso capaz sí tienen arreglado en las contrataciones)

brunovianco
Perdón, quizás me exprese mal, voy otra vez con la pregunta jajaja
Sí, en realidad es lo básico de lo básico, CI/CD, hoy no hay documentación sobre los procesos por ejemplo y se está en proceso de adoptar AWS, últimamente se estuvo laburando todo on-prem, inclusive Kubernetes
Entonces me gustaría al menos arrancar por CI/CD y que quede con los procesos definidos, después iré a otro frente

jedux
y tenes gente que banca esta idea?
o estas tipo rambo solo y en la selva?

yaco06
y la expresión de rambo es full técnica, se ve mucho

brunovianco
Todavía no sé si tengo o no la madurez para practicas de SRE, pero sí los conocimientos y las ideas

jedux
por madurez me refiero a la de la organizacion, no la de los individuos

brunovianco
Sí, hay un apoyo que costó lograr pero ya está, fue la primera etapa

yaco06
ponele, si estás solo y le querés meter, no hay tanto drama, vos podés organizar la adopción, pero si es un equipo, antes de adoptar nuevos procesos tenés que ver que manejen las herramientas básicas
ponele git, como mínimo
y armar la infra de CI/CD no es imposible, pero usarla bien es otra cuestión

brunovianco
Supuse, pero por las dudas contesté por mi parte primero jajaja, sí, algo de madurez hay, no la que quisiera pero a los suficientes niveles gerenciales como para moverme
El Git Flow ya está definido y en práctica, CI/CD está también, faltaría pulir un poquito más con los Deoloyments

yaco06
podrías comenzar por ejemplo, armando un repositorio, volcando ahí partes, componentes del código de la organización, o un proyecto, que los devs se familiaricen con git, luego avanzar a que se use una infra de CI / CD para subirlo a producción, o a una infra de staging por ejemplo
baby steps sería

brunovianco
Sí, eso está también

yaco06
y está bastante bien entonces

brunovianco
Pero el problema es que solo lo sé yo, no hay nada de procedimientos definidos mas que en mi cabeza

yaco06
quedaría pulir el deployment, ver si se puede hacer automático (mucha gente prefiere que no sea automático)

jedux
tenes que empezar por documentar entonces

brunovianco
Me estoy peleando conmigo mismo en ese sentido

jedux
puede ser automatico a todo menos a produccion, y produccion con un flag manual
y como es el onboarding de un nuevo dev al team?
quizas eso pueden laburar, la documentacion necesaria para que el ramp up sea mejor
y que un objetivo sea 'bajar las interrupciones al equipo de infra con preguntas'

brunovianco
Sí, producción en sí no tenemos porque lo maneja el cliente, pero sí tenemos entornos de staging, esos pasajes son manuales

jedux
o sea convengamos que SRE es basicamente observabilidad on steorids SLI SLO etc.

brunovianco
Claro, los Devs hoy tienen su inducción para el proyecto en cuestión, pero después yo quiero abstraer la idea de que se tengan que preocuparse por CI/CD

brunovianco
No sé si para tanto jajaja, el entorno de staging es para pruebas de volúmen y nada más

jedux
y produccion lo maneja el cliente?
o uds tambien

brunovianco
Por eso quería algo de bibliografía como para validar ideas y establecer un marco de trabajo para cuando entre más gente o me vaya al carajo jajaja

Producción lo maneja el cliente al 100%

jedux
IMO tenes que ir a mas effective devops
porque SRE estaria del lado del cliente

O’Reilly Online Learning
[Effective DevOps](https://www.oreilly.com/library/view/effective-devops/9781491926291/)[](https://learning.oreilly.com/library/cover/9781491926291/360h/)

y laburar en las metricas de la calidad del codigo, todo lo que puedas cargarle al CI/CD
y seguridad

brunovianco
Genial, esa es la idea, pero seguramente me puedo haber expresado mal

jedux
y para mi si le tiran tests a staging ahi podes sacar metricas por ejemplo y armar un error budget
pero un error budget tiene sentido para mi, si laburas con equipos que estan dispuestos a adpotar esa practica
y tambien los Service levels del staging env, etc.
Pero me suena a que vas a tener mas retorno de la inversion, si te enfocas a que el dev pueda hacer self service de todo

brunovianco
Eso es lo que tengo en mi cabeza, pero primero quiero ordenar las bases de todo, porque hay mucho desorden
Esto empezó queriendo que los Devs sean los más auto-suficientes posibles
Que dependan lo menos posible de Tecnología, porque el negocio de ellos no es el mismo, somos como un cliente más para ellos

jedux
https://twitter.com/jedux/status/1494646568036847617
Como encarar las tareas.
eso esta en el libro de lemoncelli
en 'que automatizar'
quizas te orienta en que podes encarar
y ojo, esto que estas tratando de encarar no es tarea facil

brunovianco
También, creo que eso lo tocaron en el episodio de Automation

jedux
si, exactamente fue ese capitulo

brunovianco
Hay muchos capítulos de esos GOAT que me ayudaron a validar y encarrilar mis ideas
Sí, estoy al tanto jajaja, me llevó casi 8 meses y 25 PPTs conseguir el apoyo gerencial

jedux
otra cosa que puede servirte es armar un roadmap a 1-2 años

brunovianco
El problema va a ser prometer algo en un Roadmap que después no se si voy a poder cumplir, porque hoy soy el único que se dedica a esto, aunque la idea es meter gente una vez que esté establecida el área

jedux
el roadmap es para vos solo
es simplemente para ordenarte un poco y despues ir viendo que steps son realizables para avanzar. ademas tambien para medir el 'exito'
yo se que suena re paja, pero si estas flojo de documentacion de lo que esta, vas a tener que empezar por ahi
podes mirar los niveles de madurez de cmm tambien

brunovianco
Bien, sí, efectivamente suena re paja jajaja, pero bueno, voy a tener que arrancar por el lugar que menos quería

jedux
donde sea que documentes, que todos puedan editar
y que tenga control de cambios

esto puede servir tambien para pensar un roadmap
https://itrevolution.com/the-five-time-thieves/

brunovianco
https://www.logitblog.com/the-12-steps-of-continuous-integration/ este artículo me gustó como para arrancar con una especie de manifiesto, hasta avanzar con la lectura de la bibliografía que me dejaron más arriba

**Comment by edux** [comment]
Agregado a la wiki https://github.com/sysarmy/disneyland/wiki/charla-sobre-DevOps-20220321-%23sysarmy-%23help
