### ISSUE TITLE
convertir este hilo en un .md

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#122]
https://twitter.com/baumannzone/status/1526080007218536449

como el de podcast_de_sistemas.md etc.

**Comment by Nachichuri** [comment]
Que tal suena si armo un documento compartido en Drive y lo tiro en Discord para que la comunidad entre a dejar sus propias "reviews" de las películas y después lo vuelco todo en una entry del blog? :P

**Comment by edux** [comment]
el tema es que en el blog despues se pierde en el historial, dejar un md aca me da mas friendly para hacerle referencias, que  cualquiera pueda hacer un PR y que sea mas facil de mantener, pero como prefieras.

**Comment by Nachichuri** [comment]
No lo había pensado de esa manera, es verdad...

Okey, armo un md y si te parece lo podemos pasar en las redes para que la gente se cope y manden PRs

**Comment by edux** [comment]
si, perfecto

**Comment by Nachichuri** [comment]
Creado y abierto para contribuciones

https://github.com/sysarmy/disneyland/blob/master/peliculas_de_sistemas.md
