### ISSUE TITLE
Botón de calendario en el main README

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/disneyland#124]
Sumaría meter un botón para agregar el calendar de la comunidad a Google Calendar? Si bien ya está en el [README de adminbirrator](https://github.com/sysarmy/disneyland/tree/master/adminbirrator), quizas también puede ir algo así:

![image](https://user-images.githubusercontent.com/38166071/177386895-c13311cd-4482-4ee8-861f-65aaa120dae1.png)

No se si es sumar clutter. Thoughts?

**Comment by edux** [comment]
Si mandá el PR.
