### ISSUE TITLE
importance of great finish

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#135]
para el blog https://queue.acm.org/detail.cfm?id=3293457

**Comment by jcasarini** [comment]
Agarro para traducir.
(Voy a tardar un poco mas esta vez, me voy de vacaciones)

**Comment by edux** [comment]
no hay problema!

**Comment by jcasarini** [comment]
PR creado.

**Comment by edux** [comment]
https://github.com/sysarmy/blog/pull/88 la seguimos por acá.
