### ISSUE TITLE
Link encuesta sueldo en openqube

### ISSUE THREAD

**Issue by Matgarolm** [sysarmy/disneyland#139]
Si se busca openqube en google, para poder acceder a la encuesta de sueldos, el link que sale es de la encuesta del 2021 y no la última.

Adjunto imagen
 
![unknown](https://user-images.githubusercontent.com/54144278/189183710-6e9400b8-c51f-4d93-890c-95e52441910e.png)

**Comment by Nachichuri** [comment]
Buenas, entiendo que son [sitelinks](https://developers.google.com/search/docs/advanced/appearance/sitelinks) automáticos que crea Google cuando crawlea la página y capaz le suma alguna ponderación por tráfico, hasta donde yo sé no sería editable, no se si hay alguna opción en la consola de Google Ads si se está usando. Dejo el issue abierto por las dudas.

**Comment by Matgarolm** [comment]
Yo entiendo que es lo que levanta google del sitio. Pero justamente me llama la atención que levante la vieja y no la nueva. Hay algo raro ahí.

**Comment by edux** [comment]
arreglado!
