### ISSUE TITLE
Cómo usar mirror de Sysarmy

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/disneyland#140]
Up for grabs!

Sysarmy tiene mirrors de los repos de varias distros, se puede ver acá:

https://mirrors.eze.sysarmy.com/

La idea sería tener un README que tenga instrucciones sencillas, beginner friendly, y fácilmente copypasteables de cómo poder usar los mirrors de Sysarmy como source en cada una. Se puede empezar con una y que otras personas vayan sumando.

Inicialmente se me ocurría que podía ser un README en este repo, pero se puede evaluar otra forma de presentación de la info. Por lo pronto creo que lo más directo sería forkear y mandar PR con algo redactado en un README para poder irlo avanzando entre la comunidad.

**Comment by ballesterosd** [comment]
![image](https://github.com/sysarmy/disneyland/assets/103466753/34fad3f0-4111-461c-aba7-bc6643489151)
Cerrar post? jejejej

**Comment by edux** [comment]
Si, esto murio.
