### ISSUE TITLE
Subir post al blog

### ISSUE THREAD

**Issue by ajolo2ky** [sysarmy/disneyland#141]
Subir https://medium.com/@jvmbruno-es/el-peor-d%C3%ADa-de-mi-vida-profesional-6c2d962823af al blog, haciendo la mención correspondiente al autor, link original y mantener los links a la empresa

**Comment by Nachichuri** [comment]
Agregado en sysarmy/blog#89! La semana que viene sale sysarmy/blog#88 y éste puede quedar en queue para la próxima publicación

**Comment by Nachichuri** [comment]
Published!
https://sysarmy.com/blog/posts/el-peor-dia-de-mi-vida-profesional/
