### ISSUE TITLE
para el blog "Signs you’re in a toxic work environment – and how to make it bearable" 

### ISSUE THREAD

**Issue by lole2k** [sysarmy/disneyland#145]
Traducir al español https://www.loom.com/blog/toxic-work-environment para el blog, la forma mas simple:

forkear el repo del blog
crear una branch nueva
tomar de ejemplo algun blogpost para ver el markdown y las cabeceras por ejemplo https://github.com/sysarmy/blog/blob/master/content/posts/10-proyectos-para-automation-engineers.md
google doc y google translate
fixear los errores de google translate, agregar las imagenes, etc.
mandar pull request.

**Comment by jcasarini** [comment]
Hecho.

https://github.com/sysarmy/blog/pull/97

**Comment by Nachichuri** [comment]
Published!
