### ISSUE TITLE
Don’t be arrogantly ignorant: don’t flame

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#147]
Para el blog en español: https://dev.to/wesen/dont-be-arrogantly-ignorant-dont-flame-814

**Comment by jcasarini** [comment]
Lo agarro, es cortito.

**Comment by jcasarini** [comment]
Hecho.

https://github.com/sysarmy/blog/pull/95

**Comment by Nachichuri** [comment]
Published!
