### ISSUE TITLE
Traducir "My secret life as an 11-year-old BBS sysop" para el blog

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/disneyland#155]
https://arstechnica.com/information-technology/2022/12/my-secret-life-as-an-11-year-old-bbs-sysop/

Traducir, mandar PR y revisamos :)

**Comment by jcasarini** [comment]
Buenas! Lo agarro.

**Comment by jcasarini** [comment]
@Nachichuri ya terminé con la traducción, estoy armando el post.

Tiene unos carruseles con fotos y e imágenes. Se te ocurre qué hacer con eso? Cómo replicarlo?

**Comment by Nachichuri** [comment]
Con GIFs muy feo? xD

![Peek 2023-01-02 15-22](https://user-images.githubusercontent.com/38166071/210267612-aa992434-3cd9-4d00-84db-fc99fad07513.gif)

![Peek 2023-01-02 15-24](https://user-images.githubusercontent.com/38166071/210267603-748d4b04-c238-4823-b771-5cadef27f769.gif)

**Comment by jcasarini** [comment]
![6b684d967e6a2150eb70cc330e67364b.png](https://user-images.githubusercontent.com/6942398/210267824-d0709bf6-26df-44c8-9333-ca3ccb6f35e1.png)

Bastante on point con el tema debo decir, jajaja

**Comment by Nachichuri** [comment]
Published!
