### ISSUE TITLE
Taller / Workshop de Postman

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#16]
Pensar un tallercito de Postman para dar en el museo, 101:

- instalar postman
- API's 101
- Features
- Usar algunas apis publicas para probar features como profiles & shit.

https://www.getpostman.com/

**Comment by matiasnoriega** [comment]
Dejo acá una API para testeo/aprendizaje y una alternativa online, libre y SUPER LIVIANA (en comparación) al Postman:

- [https://reqres.in
](https://reqres.in
)

- [Postwoman](https://postwoman.io)
