### ISSUE TITLE
Para subir al blog

### ISSUE THREAD

**Issue by ajolo2ky** [sysarmy/disneyland#164]
Subir https://medium.com/@jvmbruno-es/la-vida-del-sysadmin-una-historia-de-patch-tuesdays-4641bfc1aac al blog de sysarmy, con link al autor y publicación original. Ya tenemos su permiso.

**Comment by jcasarini** [comment]
Buenas!
Ahí lo armo y creo el PR.

**Comment by jcasarini** [comment]
@ajolo2ky, tiene algunos typos, se los dejo como en el original?

**Comment by jcasarini** [comment]
PR creado
https://github.com/sysarmy/blog/pull/104

**Comment by deftoner** [comment]
Perdón porlos typos :D

**Comment by jcasarini** [comment]
_tragame tierra_

Tengo tu permiso para acomodarlos @deftoner?

**Comment by deftoner** [comment]
Recien veo esto @jcasarini  obvio que si.

**Comment by Nachichuri** [comment]
Published!
