### ISSUE TITLE
Agregar para próximas encuestas

### ISSUE THREAD

**Issue by ajolo2ky** [sysarmy/disneyland#166]
Tecnologías:

- Figma

Universidades:

- Universidad Nacional de San Luis

Puestos:

- Otros

Modalidad:

- Remoto dentro de mi país

**Comment by MerendaFrancoN** [comment]
Buenas! Venía a levantar que faltaba la **Universidad Nacional de San Luis**. Gracias!

**Comment by ajolo2ky** [comment]
Agregada, gracias!

**Comment by ajolo2ky** [comment]
Agregada, gracias!
