### ISSUE TITLE
Para el blog: elasticsearch

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#171]
https://blog.devgenius.io/elasticsearch-solution-to-searching-71116220c82f

**Comment by vmariano** [comment]
Me interesa, porque me acabo de meter en un proyecto que lo usa y lo tuve que aprender.

**Comment by vmariano** [comment]
Hola, la vida me paso por arriba, aca tengo un branch con un WIP: https://github.com/sysarmy/blog/pull/114

**Comment by Nachichuri** [comment]
Genial! Sin apuro, cuando lo tengas me avisas y lo reviso (:

**Comment by vmariano** [comment]
Buenas! vuelvo como si nada con total impunidad.
Ayer meti una translation completa. ¿Las imagenes tambien requieren traduccion? ¿Como lo suelen manejar?

**Comment by edux** [comment]
Las imagenes no hace falta van como el original

**Comment by vmariano** [comment]
Agregue las imagenes del articulo original, me faltaria agregarle una imagen a la portada (acepto sugerencias). 
Hago una revision general y lo dejo listo para review. Lo mas grueso ya esta listo.

**Comment by Nachichuri** [comment]
Perfecto! Avisame y lo reviso. Quedaría para publicar a comienzos de marzo. Gracias!!

**Comment by vmariano** [comment]
Buenas! 

le pegue una corregida y actualize varias cosas rotas. Es un articulo largo, si podemos sumar mas correctores mejor.
Dejenme code suggestions o armemos discusiones sobre las partes que no cierren.

**Comment by Nachichuri** [comment]
Published! :) En unos minutos ya lo vas a ver live en sysarmy.com/blog

Muchas gracias por la traducción
