### ISSUE TITLE
Traducir para el blog: Advice for new software devs who've read all those other advice essays

### ISSUE THREAD

**Issue by Nachichuri** [sysarmy/disneyland#179]
https://buttondown.email/hillelwayne/archive/advice-for-new-software-devs-whove-read-all-those/

Traducir > Mandar PR o mail > Revisamos > Done!

**Comment by peorth80** [comment]
Agregado el PR https://github.com/sysarmy/blog/pull/116

**Comment by Nachichuri** [comment]
Published! Gracias @peorth80 :)

https://sysarmy.com/blog/posts/sugerencias-para-desarrolladores-que-recien-empiezan/
