### ISSUE TITLE
Mejorar esta respuesta: 4033 problemas al tratar de conectarme a mysql

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#22]
Esta respuesta esta bien posicionada en google, mejorarl el contenido para que tenga mas -vvvv https://help.sysarmy.com/discussion/4033/problemas-al-tratar-de-conectarme-a-mysql

**Comment by peorth80** [comment]
Es un ticket del 2018... vos decis que tiene sentido mantenerlo "actualizado" al 2020? porque la verdad que no poder conectarse a un mysql puede ser por mil motivos (contraseña, puertos cerrados, etc, etc).

**Comment by ajolo2ky** [comment]
Sí, agregaría respuestas de posibles opciones de troubleshooting

**Comment by GeekBeardLinks** [comment]
Estoy lejos de mis días de (W|L)AMP, pero tratando de refrescar mi memoria buceando un rato en internet en busca de tips y esas cosas, para mí más o menos el troubleshooting va por estas líneas:
 
1. Mirar si el proceso está corriendo
2. Chequear en que puerto está corriendo
3. Mirar si se tiene privilegios para conectarse desde donde se hace conexión, sea `localhost` u otro lugar
4. Mirar los logs en busca de errores

¿Faltará algo que chequear?

1 y 2 varían bastante dependiendo si se está usando WampServer, XAMPP, MySQL instalado en el SO (Windows|Linux), containers, etc. 

Para 4 me parece que conviene mostrar donde mirar para ver donde está el log.

¿Les parece ir haciéndolo de manera iterativa incremental en el post?

Dejo algunas referencias:

- [Tips de troubleshooting de WampServer](http://forum.wampserver.com/read.php?2,134915) Muy completo
- [Ver si MySQL está corriendo en Linux](https://www.cyberciti.biz/faq/how-to-find-out-if-mysql-is-running-on-linux/)
- [Respuesta de SO de como chequear las variables de MySQL para saber donde están los logs](https://stackoverflow.com/a/37685324) 

Saludos!

**Comment by edux** [comment]
Agregalo en /help!

**Comment by GeekBeardLinks** [comment]
Perfectirijillo.

Calculo que lo hago tranquilo el finde que no estoy a las corridas.

Prometo no colgar.

**Comment by GeekBeardLinks** [comment]
> Agregalo en /help

@edux presumí que te referías a agregarlo en el hilo, pero ahora me doy cuenta ahora que el mismo está cerrado. :facepalm: 

¿Decías de abrir un nuevo hilo y que deje la respuesta ahí? ¿Hacer eso no mata un poco la idea de usar ese hilo porque está bien posicionado en Google?

Mientras me aclaran que prefieren hacer, dejo* acá la respuesta formateada, así si me abducen aliens :alien:, me cae un problema productivo :fire::fire::fire: o me agarro alto empacho de churros de El Topo, etc., pueden hacer tranquilamente C&P. 

*Claramente desde que escribí esto y traté de armar la respuesta pasó más tiempo del que esperaba y me quedé a medio camino. Estoy acostumbrado a la receta APB por el laburo... :shrug:

Probablemente haya horrores de redacción, así que cualquier comentario por ese lado es más que bienvenido.

Los links que aparacen son las imágenes que no subí (mi idea original era redactarlo local y hacer C&P acá, pero bueno, pasaron cosas y prefiero que vean que es que no colgué).

Seguiré editando y agregando acá hasta terminar y después hago lo que sugieran que haga sobre `/help`.

-----
En general para analizar el problema de conexión a la base de datos MySQL lo que uno podría hacer es lo siguiente:

1. Verificar si el proceso de la base de datos (BDD) está ejecutándose
2. Verificar la conexión a la BDD
   1.  Verificar los parámetros de conexión del programa con el que se quiere conectar a la DB 
   2. Verificar que el puerto está corriendo el proceso de la DB coincide con el puerto de la conexión
   4. Verificar si el usuario tiene privilegios para conectarse
3. Ver los logs de la DB en busca de errores

> **NOTA**
> 
>  Si la conexión a la BDD se hace de manera remota (es decir el programa y la BDD están en distintos equipos), también habría que verificar que se pueda llegar desde donde se ejecuta el programa hasta donde está ejecutando el proceso de la DB y que el puerto es visible. 
>
> Por tratarse de `WampServer` estoy  asumiendo que programa y BDD están en el mismo equipo.

Veamos los pasos descriptos arriba en detalle para el caso puntual `WampServer`:

## 1. Verificar si el proceso de la base de datos (BDD) está ejecutándose

### Desde WampServer

1. Hacer click izquierdo sobre el ícono de WampServer
2. Ir a MySQL
3. Ver el estado del proceso
   1. El proceso está ejecutándose si se vé un tilde verde a la izquierda de `Service administration 'wampmysqld64'` en WampServer de 64 bits o  `Service administration 'wampmysqld'` para la versión de 32 bits. ![Proceso BDD ejecutándose visto desde WampServer](./WampServer/troubleshooting-000-wampserver-process.jpg)

   2. Si en `Service administration 'wampmysqld64'` (o `Service administration 'wampmysqld'`) no aparece el tilde verde posicionarse arriba de `Service administration 'wampmysqld64'` (o `Service administration 'wampmysqld'`), se abrirá un nuevo menú, sobre este nuevo menú hacer click en `Start/Resume Service`.

### Desde servicios de Windows

1. En la cuadro de búsqueda de Windows, buscar la aplicación `Run` o `Ejecutar` (dependiendo si el idioma de Windows es inglés o español) y ejecutarla. ![Ver estado del proceso BDD desde WampServer](./WampServer/troubleshooting-001-run.PNG)
2. En el cuandro de diálogo de `Run` (o `Ejecutar`) ingresar `service.msc` y presionar `OK`. ![Ver estado del proceso BDD desde WampServer](./WampServer/troubleshooting-002-services-msc.PNG)
3. En la ventana de `Services` (o `Servicios`) buscar el servicio con nombre `wampmysqld64` para `WampServer` de 64 bits (o `wampmysqld` para la versión 32 bits).
   1. El servicio está corriendo si el `Status` (o `Estado`) es `Running` (o `En ejecución`).
   2. Si no aparece valor en la columna `Status` (o `Estado`) hacer click sobre la línea del servicio, luego hacer click derecho y en el menú que aparece hacer click sobre `Start` (o `Iniciar`).


## 2. Verificar la conexión a la BDD
### 2.1. Verificar los parámetros de conexión del programa con el que se quiere conectar a la DB. 

Mirar en el programa se quiere conectar a la BDD los valores de conexión:
- `host`: donde corre este caso debería figurar `localhost`
- `port`: es el puerto que utiliza la BDD para recibir peticiones. Por defecto MySQL utiliza `3306`
- `user`: el usuario con el cual se quiere conectar a la DBB
- `password`: contraseña del usuario (`user`) 

### 2.2. Verificar que el puerto está corriendo el proceso de la DB coincide con el puerto de la conexión

Si el valor del puerto obtenido con este verificación coincide con el puerto que utiliza el programa continuar con los chequeos. 

En caso contrario cambiar el valor del puerto utilizado por el programa al que utiliza MySQL y volver a ejecutar el programa para ver si se solucionó el problema. 

### Verificación del puerto utilizado desde WampServer
1. Hacer click derecho sobre el ícono de WampServer
2. Ir a Tools 
   1. En el menú aparecerá el ítem `Test port 3306` y si se cambió el puerto desde `WampServer` también aparecerá el ítem  `Test MySQL port used: PUERTO` donde `PUERTO` es el valor del puerto utilizado por MySQL.
      1. Hacer click en `Test port 3306` si sólo aparece dicho ítem. Esta acción abrirá una ventana que mostrará el resultado del chequeo
      2. Hacer click `Test MySQL port used: PUERTO` si sólo aparece dicho ítem. Esta acción abrirá una ventana que mostrará el resultado del chequeo
      3. Si el chequeo en ambos casos falla y el proceso está ejecutándose hacer lo indicando en esta sección en `Desde línea de comando`

#### Desde línea de comando

1. Abrir `CMD` como `Administrator` (`Línea de comando` como `Administrador`)
2. Ejecutar `netstat -a -b` 
3. Buscar en la salida los puertos asociado al proceso `mysqld`

### 2.3. Verificar si el usuario tiene privilegios para conectarse

## 3. Ver los logs de la DB en busca de errores

**Comment by edux** [comment]
ooops se cerro en la migracion, yo despues paso esto ahi, gracias!

**Comment by edux** [comment]
Ahi actualize el hilo https://help.sysarmy.com/discussion/4033/problemas-al-tratar-de-conectarme-a-mysql pero me parece que faltan unas images que referenciaste, esas estan en alguna de las otras paginas como para que las suba o linkee en el reply?

**Comment by GeekBeardLinks** [comment]
> Ahi actualize el hilo https://help.sysarmy.com/discussion/4033/problemas-al-tratar-de-conectarme-a-mysql pero me parece que faltan unas images que referenciaste, esas estan en alguna de las otras paginas como para que las suba o linkee en el reply?

Faltan cosas. Edito mi respuesta arriba, así tirás el C&P con todo. 

Espero terminar hoy.  

Hermosa manera de pasar el feriado (va sin ironía, ni sarcasmo, bueno tal vez un poco JAJAJA! al menos no tengo que revisar PRs del Team).

**Comment by edux** [comment]
Ahi subi todo lo ultimo, gracias!
