### ISSUE TITLE
Mejorar el landing del mirror.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#25]
La landing page del mirror es bastante simple http://mirrors.eze.sysarmy.com/ si alguien quiere usarla como proyectito para mejorar skills de frontend los requerimientos son:
- tiene que funcionar en plain text
- html-css only, nada de javascript.
- pueden agregar una firma si quieren.

**Comment by edux** [comment]
@thisisFlawsome se voluntario, no te puedo poner como assignee yet tengo que agregarte en org y permissions y es tarde y tengo sueño. XD

**Comment by peorth80** [comment]
Ahi la asigne ;)

**Comment by cdutten** [comment]
Buenas :wave: 

Puedo dar una mano por aca?
El finde me puse a probar y salio esto
[Figma draft](https://www.figma.com/proto/VM34D0cMVIufEKTWxR0JkG/Sysarmy-mirror-web?node-id=14%3A6&scaling=min-zoom)

**Comment by peorth80** [comment]
> 
> 
> Buenas 👋
> 
> Puedo dar una mano por aca?
> El finde me puse a probar y salio esto
> [Figma draft](https://www.figma.com/proto/VM34D0cMVIufEKTWxR0JkG/Sysarmy-mirror-web?node-id=14%3A6&scaling=min-zoom)

Jajajaja que copado! No queres hacer un PR asi lo ven los chicos? @edux @ajolo2ky :D

**Comment by cdutten** [comment]
Aun es solo un draft en Figma. Decias de mandar pr con el draft de Figma?

Si me dan el okay mando pr con el HTML+CSS.

**Comment by edux** [comment]
este fin de semana lo miro

**Comment by edux** [comment]
para mi va, lo que si las imagenes de los sponsors (logos) las dejaria en
imagen.

**Comment by cdutten** [comment]
Buenisimo.
Voy a cambiar lo de los logos y pasarlo por el slack/discord/irc para pedir opiniones.

**Comment by cdutten** [comment]
Cambie el background por fotos de Unsplash.

Opcion 1
https://www.figma.com/proto/VM34D0cMVIufEKTWxR0JkG/Sysarmy-mirror-web?node-id=81%3A2&scaling=min-zoom

Opcion 2
https://www.figma.com/proto/VM34D0cMVIufEKTWxR0JkG/Sysarmy-mirror-web?node-id=14%3A6&scaling=min-zoom

Lo dejo por slack/discord/irc tambien
