### ISSUE TITLE
Armar un articulito de como usar el editor de /help

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#26]
Basicamente tomar la info de aca https://success.vanillaforums.com/kb/articles/13-rich-editor#important-functions y llevarla a un post en /help en español para que quede en top category asi todos ven como usar el code block, titles etc asi deja de estar tan plano todo o requerir que un admin edite las preguntas.

**Comment by peorth80** [comment]
![2020-06-02 20_13_54](https://user-images.githubusercontent.com/16003799/83578632-a46d3600-a50d-11ea-8377-ad68423ce861.png)

:D 
Lo hago en dos partes?

**Comment by edux** [comment]
Awesome, thanks!
