### ISSUE TITLE
translate to ES

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#27]
Para el blog, algo en criollo https://adayinthelifeof.nl/2020/05/20/aws.html

**Comment by peorth80** [comment]
Te parece tirarlo a un google docs y despues te paso la URL? Si es asi, me lo auto-asigno. Tnx!

**Comment by edux** [comment]
Si, el gdoc va, en todo caso postealo aca el link con permissions de suggestions only para cualquiera y lo traducimos entre todos.

**Comment by edux** [comment]
https://medium.com/teamzerolabs/5-aws-services-you-should-avoid-f45111cc10cd

**Comment by marcorichetta** [comment]
Buenas!

Vine buscando [easter eggs con platita](https://youtu.be/Lt7JojKx320?t=4145) y terminé aprendiendo sobre no sé cuantos servicios de Amazon (ya estoy para el re:Invent).

Comparto el [documento](https://docs.google.com/document/d/1sAIfrfUA3aV6OknRgdfMOLLDPStZP5PhFn0rpOQj5g0/edit?usp=sharing) con permiso para que cualquiera pueda comentar. Si es necesario le cambio el ownership o lo que sea.

- Tiene menos consistencia de la que me gustaría (Español/Spanglish/Cordobés).
- Dejé algunos comentarios con dudas.
- Algunos servicios ya salieron de preview y se podrían completar las descripciones pero ~alergia a la pala~ considero que no sé lo suficiente sobre AWS. (?)

Sólo espero pase los estándares de Sysarmy.

**Comment by edux** [comment]
Listo! sale mañana. Gracias!
