### ISSUE TITLE
Agregar proyectos en el repo de Github

### ISSUE THREAD

**Issue by peorth80** [sysarmy/disneyland#29]
Se me ocurre que podemos agregar proyectos aca en Github para organizar un poco mas los tickets
Algunos que me vienen a la mente:
- Blog
- Help
- Github 
- Discord
- Slack
- Integraciones 
- Mirror
- Podcast

Que les parece?

**Comment by edux** [comment]
Ahi agregue un par de projects vamos viendo si sirve y le damos mas rosca, si qures hacer triage mandate nomas.
