### ISSUE TITLE
article to spanish

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#4]
Get this translated to spanish https://www.jonobacon.com/2019/01/21/get-your-cfp-session-picked/ for the blog.

**Comment by yojota** [comment]
Eng: I am currently in the process of improving my English. I will try to help with this and at the same time it will help me to continue learning.
Esp: Actualmente estoy en un proceso de mejorar mi inglés . Voy a intentar ayudar con esto y al mismo tiempo me sirve para seguir aprendiendo.
