### ISSUE TITLE
logtop: para traducir al ES y ampliar.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#41]
https://www.cyberciti.biz/faq/linux-unix-logtop-realtime-log-line-rate-analyser/ en conjunto con goaccess y alguna otra tool de logs. Para un blogpost o algo en /help.

**Comment by gnpar** [comment]
Unos grosos lo mostraron muy bien en youtube:

https://www.youtube.com/watch?v=ByWLMRiISm4

;-)
