### ISSUE TITLE
proxyjump + sshuttle

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#43]
https://medium.com/maverislabs/proxyjump-the-ssh-option-you-probably-never-heard-of-2d7e41d43464 algo para refactorear en español.

**Comment by GeekBeardLinks** [comment]
Refactorear en español == traducir? O hay algo que no te gusta del artículo? O es más bien algo que le falta?

**Comment by edux** [comment]
La verdad no me acuerdo, seria leer el articulo y si es algo piola traducir al español para mandar al blog.

**Comment by GeekBeardLinks** [comment]
JAJAJA! Ok. Lo traduzco, lo dejo acá y vemos. ¿Les parece?

**Comment by edux** [comment]
Si, pero tiralo a un gdoc y pasale autotranslate no te gastes demasiado, o
sea lee la autotraduccion para corregir los sin sentidos.

**Comment by GeekBeardLinks** [comment]
![u](https://media.giphy.com/media/MBOmycC7JUc8xJAnaJ/source.gif)

**Comment by GeekBeardLinks** [comment]
Bueno el documento traducido está [acá](https://docs.google.com/document/d/1fkKODXeeTfXwS4CmQJCa8Q-9D08vn06CH9tiK3WvCf4/edit?usp=sharing).

El link es está en modo sólo lectura, así que si quieren editar pidan permisos y se los doy.

**Comment by edux** [comment]
Salio! https://sysarmy.com/blog/posts/proxyjump-tuneles-ssh/
