### ISSUE TITLE
lista de podcasts: agregar una mini descripcion de cada uno.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#46]
En https://help.sysarmy.com/discussion/4719/podcasts-de-sistemas hay una lista de podcasts, la idea seria poner debajo de cada link una mini mini mini reseñita sobre que es el podcast, puede ser la misma sinopsis que tiene el mismo podcast en spotify o donde sea.

Si alguien quiere armarlo se lleva la lista a un google doc, le agrega el texto que va y pastea el link aca. Yo despues edito el post en /help.

**Comment by gfxargentina** [comment]
Hola, quiero hacer este issue, cuando tenga el link con las reseñas lo subo aqui, saludos

**Comment by gfxargentina** [comment]
listo, 

https://docs.google.com/document/d/1vFlY9BDc653c9CC1pwnzpwTYB-8rO_jAjfzrCZVJ3Ww/edit?usp=sharing

**Comment by edux** [comment]
Gracias por la buena onda, el https://help.sysarmy.com/discussion/4719/podcasts-de-sistemas ya quedó y ademas sume un file en markdown para que podamos trackearlo aca tambien.
