### ISSUE TITLE
Help improvement: Sistemas de chat opensource

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#47]
Tenemos esta pregunta en /help https://help.sysarmy.com/discussion/3140/sistema-web-chat-interno y seria deseable tener una lista más extensiva y "completa" de las opciones que hay en 2020 para resolver esa problemática. Sería algo similar a esto https://github.com/sysarmy/disneyland/blob/master/podcasts/podcasts_de_sistemas.md

### Nombre de la tool
pequeña descripcion
- [link al site](1)

No hace falta que lo editen en /help porque hay una limitacion de 8000 chars en cada reply. pueden agregar un gdoc link aca o mandar un PR con un file en markdown en una carpeta /help/

**Comment by Juansegundocabrera** [comment]
Lista de chats open source recomendados 2020:

**Slack (Freemium)**

La “vieja confiable”, aunque hayan pasado varios años desde su salida aun así se mantiene firme entre las opciones más recurridas por las empresas.

**Lo bueno** de Slack: Actualizaciones relativamente seguidas (última actualización julio 2020), Slack se integra con docenas de otros servicios, incluidos Dropbox, Google Drive, GitHub, Datadog, Asana, Mailchimp. Además, cuenta con la mayoría de las funciones de mensajería instantánea como videollamadas en grupo, individuales, compartir pantalla, etc. El plan más caro cuesta USD12,50 al mes, lo que no es un gran gasto para una empresa teniendo en cuenta las ventajas comunicativas que te otorga. Finalmente, su gran función de búsqueda que ayuda a tener a mano siempre los archivos, mensajes, todo lo que tengas que acordarte.

**Lo malo** de Slack: La versión gratuita de Slack viene con varias cláusulas restrictivas para los usuarios. Por ejemplo, el espacio de almacenamiento de datos está limitado a un máximo de 5 GB en toda la organización, demasiado insuficiente para las entidades comerciales de gran escala. Además, solo se puede buscar en los últimos 10,000 mensajes.


**Troop Messenger (premium)**

En este caso estamos hablando de algo más actual, la aplicación salió en 2017, por lo que cuenta con varias de las características de las otras aplicaciones ya nombradas y hasta mejoradas.

**Lo bueno** de Troop: Al ser una aplicación lanzada 4 años después que la aplicación anterior mencionad, dio la posibilidad de analizar y agregar mejoras a cada una de sus características. Cuenta con un servicio de atención al cliente desde el primer plan de todos, tiene la posibilidad de conectarse desde cualquier dispositivo y hasta brinda métodos de seguridad avanzados como tecnología de huellas dactilares, PIN o el método que más te guste.

**Lo malo** de Troop: La versión gratuita solo es de 7 días, por lo que al finalizar deberás elegir uno de los planes de pago. El primer plan de pago, aunque no es caro (USD 1) por mes, cuenta únicamente con 150GB de memoria por lo que no es una opción para emprendimientos de gran tamaño.


**Flock (Fremium)**

 El preferido de McDonals, y no por cualquier motivo, esta es una aplicación muy potente, pero hay que saber darle un buen uso.

**Lo bueno** de Flock: Flock ofrece planes gratuitos y Pro, pero en el plan gratuito no impone ningún límite a la cantidad de mensajes, canales o clientes que tiene en las cuentas, ni limita la cantidad de integraciones de aplicaciones que puede configurar, si se sabe utilizar no es necesario pagar absolutamente nada, aunque hay buenas ventajas al pagarlo como la prioridad en atención al cliente o la posibilidad de crear canales infinitos tal cual lo hacemos en discord.

**Lo malo** de Flock: Al igual que Slack, también limita la funcionalidad de búsqueda hasta 10,000 mensajes. Una cuenta gratuita permite compartir únicamente hasta 100 archivos, cada uno con un tamaño máximo de 100 MB.


**MatterMost (Fremium)**

En este caso al buscar información para esta respuesta encontré datos muy variados, sin embargo, es una aplicación con mucho potencial, aunque debe tenerse conocimientos de host para poder instalar algunas extensiones.

**Lo bueno** de MM: La interfaz es bastante auto explicativa. Por eso la aceptación del usuario es bastante buena. La personalización de la interfaz es sencilla y se puede realizar a nivel de usuario. La comunidad de código abierto alrededor de Mattermost es realmente agradable y acogedora. Las aplicaciones para todos los sistemas operativos están disponibles y son fáciles de usar una vez configuradas manualmente. La escalabilidad nunca fue un problema con más de 1000 usuarios.

**Lo malo** de MM: Configurar integraciones es más complejo que con Slack, donde las integraciones se pueden instalar con un clic en el backend. Hay un directorio de aplicaciones, pero las aplicaciones deben configurarse manualmente. Una vez configurados, simplemente funcionan. Los webhooks entrantes son la única excepción; funcionan fuera de la caja. El rendimiento móvil está mejorando gradualmente, pero aún no está a la altura de Slack. La aplicación de Windows aún no está lista para implementaciones a gran escala a través de políticas de grupo.


**Rocket.Chat (Premium)**

Una de las aplicaciones de uso mas simplificado, no hay que tener conocimientos de nada tanto para usarla como para instalar funciones.

**Lo bueno** de Rocket: Cuenta con una muy buena función de compartir archivos, podes compartir hasta carpetas enteras en segundos, tiene funciones similares a las de Discord donde se pueden crear fácilmente nuevos canales, administrar los roles y nombres de cada uno. Y finalmente la característica mas destacada, se puede instalar en tu propio servidor (autohost) por lo que van a contar con la seguridad propia de sus servidores, mayor velocidad y privacidad.

Lo malo de Rocket: Actualmente está en desarrollo y hay errores que perjudican y molestan, por ejemplo, no hay posibilidad de llamada de voz, por lo que al iniciar una videollamada lanzara avisos múltiples de que hay usuarios sin cámara. Siguiendo con errores, las notificaciones a veces se traban y no hacen sonido, ni avisan.


**Zulip (Fremium)**

Zulip es la aplicación de chat de código abierto más activa en GitHub y tiene más de 350 colaboradores de todo el mundo.

**Lo bueno** de Zulip: Uno de los pocos Códigos Abiertos de la lista, cuenta con una comunidad inmensa que aporta y brinda ayuda a los mismos usuarios, es bastante intuitivo el manejo dentro de la aplicación. En lugar de salas o canales, Zulip se basa en temas. Esto le permite tener múltiples conversaciones al mismo tiempo sin que las conversaciones interfieran entre sí.

**Lo malo** de Zulip: Curva de aprendizaje ligeramente más pronunciada en comparación con otros chats grupales, pero mejor experiencia de usuario a largo plazo, su plan gratuito únicamente te permite subir archivos que pesen menos de 5GB y el historial de los últimos 10.000 mensajes (para evitar esto hay que instalar tu propio servidor).


**Matrix (Free)**

Matrix es un chat estándar de código abierto que define API HTTP simples para que los desarrolladores puedan escribir fácilmente sus propios clientes, bots, puentes o servidores.

**Lo bueno** de Matrix: Matrix está descentralizada, no hay un punto central por el que pasa la información y, por lo tanto, no hay un punto central de falla o control. Matrix proporciona una encriptación de punta a punta, esto asegura que sólo los destinatarios previstos puedan descifrar sus mensajes, mientras que avisa si se añade algún dispositivo inesperado a la conversación.

**Lo malo** de Matrix: No podés comprobar automáticamente las claves de tus destinatarios. Sólo manualmente. Ha sufrido ataques de hackeos en 2019 lo que hizo que todos los historiales de chats anteriores a ese momento se pierdan, aunque desde ese momento implementaron más medidas de seguridad.

**Comment by edux** [comment]
all done
