### ISSUE TITLE
[encuesta] Agregar opciones para socies de cooperativas en las encuestas

### ISSUE THREAD

**Issue by carolang** [sysarmy/disneyland#54]
Básicamente la idea es que si estás en una cooperativa ni sos freelancer ni estás en relación de dependencia, pero tiene aspectos de las dos cosas.

En concreto los cambios para que la encuesta nos represente (al menos los que me parecen a mí) serían estos:
- Tipo de contrato: debería tener una opción "Socie de una cooperativa"
- A los salarios les decimos "retiros", así que cuando pregunta "Salario bruto" y "Salario neto" podría decir "Salario/Retiro bruto" y "Salario/Retiro neto". Esto igual no es importante, se entiende si dice solamente salario.
- Donde pregunta si recibís un bono, y pregunta a qué está atado, debería haber una opción que sea "Votado/por decisión colectiva". Además de esto, creo que esa pregunta debería dejar que contestes más de una opción en vez de la opción "una mezcla de las anteriores".
- Donde dice "Cantidad de empleados" por ahí estaría bueno cambiarlo por "Cantidad de personas en la empresa" o "Tamaño de la empresa" porque en nuestro caso la cantidad de empleades es 0.

**Comment by edux** [comment]
Modificado!
