### ISSUE TITLE
IRC: Cloak projects?

### ISSUE THREAD

**Issue by peorth80** [sysarmy/disneyland#56]
Aca pgreco en IRC comenta que FreeNode tiene formas de ocultar los hosts/ips de ciertos proyectos, bajo algo llamado cloak
https://freenode.net/kb/answer/cloaks

_Project cloaks typically take the form project/role/user, for instance freenode/staff/bigpresh (though some take other forms). They are designed to demonstrate that the user is connected to a project in some way. Different projects use cloaks for various roles—some only use them for their core team, some will assign user cloaks as well._

_Project cloaks can only be requested by a registered group contact of an already registered group—they should contact a member of freenode staff to request that a user be given a project cloak._

Por ahi se podria averiguar para configurar **Sysarmy** como proyecto, y ponerle un cloak?

**Comment by sGoico** [comment]
Estuve chateando con e, staff de Freenode. Me hizo varias preguntas sobre que tipo de proyecto era sysarmy.
Le expliqué, le pasé links de la pagina de sysarmy y de nerdearla y casi que lo convencí.

Hay que enviar un mail con origen que demuestre afiliación con el proyecto (@syarmy.com) comentando todo lo mismo que ya me preguntó por chat:

Nombre del proyecto/comunidad, breve descripción, propósito, URLs de páginas que se tengan, eventos que se han organizado y cualquier información que se considere de relevancia.

Con esa información ellos evalúan si se le puede dar el estatus de "grupo" a la comunidad y recién ahí se pueden solicitar las famosas cloaks.

El mail debe enviarse a: projects@freenode.net
