### ISSUE TITLE
Agregar más canales de youtube

### ISSUE THREAD

**Issue by diego-go** [sysarmy/disneyland#61]
#60 

### David Bombal
Want to learn about IT? Want to get ahead in your career?  Well, this is the right place! 

On this channel, I discuss Python, Network Automation, Ethical Hacking, Networking, SDN, CCNA, Virtualization and other IT related topics.

- [David Bombal](https://www.youtube.com/c/DavidBombal)

### Craft Computing

 Computer builds, tutorials, reviews, news and information, presented the only way I know how.

- [Craft Computing](https://www.youtube.com/c/CraftComputing/about)

### Techno Tim

 I make videos that help people do awesome things with technology.

- [Techno Tim](https://www.youtube.com/c/TechnoTimLive)

### Lawrence Systems / PC Pickup

We discuss and create tutorials for firewalls, storage solutions, MSP tools, security tools and open source topics. 

- [Lawrence Systems](https://www.youtube.com/user/TheTecknowledge/about)

**Comment by edux** [comment]
Fixed, added them here https://github.com/sysarmy/disneyland/commit/83a48ac5b383aced899319d90457222f7674e667
