### ISSUE TITLE
Traducir charla de Maddog

### ISSUE THREAD

**Issue by rhapsodygirl** [sysarmy/disneyland#65]
Necesitamos traducir la charla de Maddog.

Dejo el srt para que la traducción sea exacta.
[maddog.srt.zip](https://github.com/sysarmy/disneyland/files/5127076/maddog.srt.zip)

**Comment by edux** [comment]
@rhapsodygirl te fijas lo que mergie en https://github.com/sysarmy/disneyland/pull/82 a ver si con eso estamos?
