### ISSUE TITLE
blog post nyt

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#7]
traducir https://www.nytimes.com/2019/02/13/magazine/women-coding-computer-programming.html

**Comment by GeekBeardLinks** [comment]
Mientras espero que pulamos detalles para cerrar la PR #22, voy a empezar a traducir esto.
 
Salvo que me digan otra cosa, voy a ir dejando la traducción más abajo.

**Comment by edux** [comment]
no hagamos este ya hay contenido de este tipo publicado por otras
comunidades.
