### ISSUE TITLE
[encuesta] Aclarar cantidad de empleados para empleados públicos

### ISSUE THREAD

**Issue by seppo0010** [sysarmy/disneyland#71]
Es medio rara la pregunta si trabajás para el estado. ¿Se cuenta todo el estado, un ministerio, una subsecretaría? No sé cuál es la respuesta correcta

**Comment by edux** [comment]
Ahi agregué una salvedad en la descripción, seria cantidad de personas en tu organismo / ministerio. podemos volver a iterar en la proxima.
