### ISSUE TITLE
[home bankings] mejorar test de BBVA

### ISSUE THREAD

**Issue by komodin** [sysarmy/disneyland#77]
### Para el uptime robot de los home bankings.

En el HB del BBVA el 99% de las veces funciona la página de login, pero con un test simple de login con data cualquiera, podés probar si funciona el servicio.

Cuando se va de viaje (que tira el error "Banca Online no se encuentra disponible temporalmente. Intente nuevamente en unos minutos."), este endpoint devuelve 500 por más que los datos enviados no sean reales ni correctos.

Si el login es correcto o fallido, devuelve 200.

Estaría bueno ver si se puede modificar el test y hacerlo así, porque BBVA siempre dice 100% pero muchas veces está re caído.

Un riesgo sería que por tantos logins fallidos banneen la IP desde la que se ejecuta el test. Desconozco cuál es el rate de testeo ni si el BBVA te bannea después de muchos intentos fallidos, más allá de que si fuese un usuario real se bloquearía.

curl de ejemplo, no creo que sean necesario todos los headers, así salió del "copy as curl" del browser:

```
curl 'https://online.bbva.com.ar/fnetcore/servicios/login/prelogin' \
-X 'POST' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Content-Type: application/json;charset=utf-8' \
-H 'Origin: https://www.bbva.com.ar' \
-H 'Referer: https://www.bbva.com.ar/fnetcore/loginClementeApp.html' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15' \
--data-binary '{"documento":{"tipoDocumento":{"codigoTipoDocumento":"0","descripcionCorta":"","descripcion":""},"numeroDocumento":"12312312","genero":""},"usuario":"tuvieja","claveDigital":"tuvieja","versionFront":"20201002.1942"}'
```

En resumen:

1. - [ ] Chequear si se puede configurar un POST para el test en uptimerobot
2. - [ ] Probar desde algún lado si después de un cierto periodo de tiempo te bannea la IP
3. - [ ] En caso de que no bannee la IP, configurarlo en uptimerobot

**Comment by edux** [comment]
Estamos usando el free tier de uptime robot y no permite editar headers, ni method ni nada. Si en algun momento lo cambiamos revisamos. Gracias!
