### ISSUE TITLE
Armar templates de ejemplo para CV de "Mi primer trabajo en sistemas"

### ISSUE THREAD

**Issue by peorth80** [sysarmy/disneyland#78]
Armar un par de curriculums para "Mi primer trabajo en sistemas", para poder demostrar lo que estamos aprendiendo y donde nos enfocamos al buscar el primer trabajo en IT

Se me ocurre que inicialmente podriamos tener uno para desarrolladores (agnostico de la tecnologia) y otro para sysadmins / devops

**Comment by edux** [comment]
for the record, ya hay alguien trabajando en esto.
