### ISSUE TITLE
Worst monitoring solution ever.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#83]
- alguien conoce alguna tool que te tire mensajes a los logged users por ssh que el / esta sin espacio?
Y con cron df y wall se puede inventar un one liner sencillo
Siempre podes meter un script mas en /etc/profile.d 
No les avisa mientras están logueados pero les avisa cuando se loguean
hacelo con systemd :P
snmp + syslog-ng ?
Por que no agregarlo al /etc/bashrc? si necesitas que solo se ejecute al conectar por ssh lo wrappeas con un if detectando SSH_CONNECTION
en etc cron.d un *** bash pocoespacio.sh
y poco pocoespacio.sh:
echo df con poco espacio
con inotify/fanotify no se podrá? digo por si la necesidad es monitoreo constante y no un cron
for i in /dev/pts/* ; do echo “libera espacio chatumá. Primer aviso” > $i ; done
systemd.timers
Snmp literalmente está hecho para esto
con bpf

**Comment by sebaminguez** [comment]
Yo modificaria $PS1 cosa que lo vean en el prompt.
Se actualiza en cada comando y puede ser multilinea.
