### ISSUE TITLE
understanding-bash-fork-bomb/

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#85]
https://www.cyberciti.biz/faq/understanding-bash-fork-bomb/

**Comment by edux** [comment]
Pasitos simples:

Forkear https://github.com/sysarmy/blog/tree/entendiendo-fork-bomb-bash
El file para subir el articulo en español https://github.com/sysarmy/blog/blob/entendiendo-fork-bomb-bash/content/posts/entendiendo-la-fork-bomb-de-bash.md

una vez que el contenido esta como para ser revisado hacer un pull request al repo y lo revisamos.

**Comment by efsbl** [comment]
Perfecto

**Comment by edux** [comment]
https://github.com/sysarmy/blog/pull/24/files
