### ISSUE TITLE
Link roto - Dataset de encuesta de sueldos 2021.1

### ISSUE THREAD

**Issue by maia-n** [sysarmy/disneyland#89]
Apunta a https://sysarmy.com/blog
Página> https://sueldos.openqube.io/encuesta-sueldos-2021.01/

**Comment by edux** [comment]
Es generico el link, pero los datos estan https://sysarmy.com/blog/posts/resultados-de-la-encuesta-de-sueldos-2021-1/ es medio imposible rebuildear esos micrositios. Asi que wont fix.
