### ISSUE TITLE
Join channel if user picks role.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#91]
Algo que quisiera configurar para algunos canales es que solo te sume si vos activamente elegis un rol, vi que usan reactions a algun mensaje, la idea seria que al menos:

- shithappens
- parentarmy

sean opcionales.

**Comment by peorth80** [comment]
https://www.wikihow.com/Add-Reaction-Roles-to-a-Discord-Server-on-PC-or-Mac

**Comment by peorth80** [comment]
My job here is done
