### ISSUE TITLE
Mejorar el readme del blog para las contribuciones.

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#96]
Este file del repo del blog https://github.com/sysarmy/blog/blob/master/readme.MD esta bastante áspero y desordenado. El procedimiento es sencillo pero ayudaria si alguien puede expandirlo un poco y ordenar la secuencia para que sea clara y limpia. 

El objetivo final, es que sea facil para cualquier persona saber como se puede contribuir con un blog post.

**Comment by Nachichuri** [comment]
Buenas, armé una versión nueva del README con más referencias y un poco más de documentación. De todas maneras queda el canal abierto si se quiere modificar o agregar algo.

**Comment by edux** [comment]
Gracias!
