### ISSUE TITLE
agregar el podcast de dominio digital

### ISSUE THREAD

**Issue by edux** [sysarmy/disneyland#97]
Agregar esto https://open.spotify.com/show/4e2INdQiaz6wMGm8KhqJY3?si=8RnFgRN0Rp-DIqQM_f8MTQ&nd=1 con el formato del file a este file https://github.com/sysarmy/disneyland/blob/master/podcasts_de_sistemas.md

Steps:

- Fork repo disneyland
- agregan la entrada al final de Español
- mandan pull request
- sentir satisfaccion cuando lo mergeamos.

**Comment by dariosusman** [comment]
Ahi lo agrego
